// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrdlexmxlzvsarqdgowf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZGxleG14bHp2c2FycWRnb3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDI4NjksImV4cCI6MjA3MjMxODg2OX0.QhWVf73sbKNwPONbMXegKQcCwVH3PeAKVAHD0GyDtQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});